bin/Runes.exe: Runes/Runes.cs Runes/Properties/AssemblyInfo.cs
	buildsln Runes.sln
#	mdtool build -t:Build -f:JakobCWH.sln

clean:
	rm -rf Runes/obj Runes.suo
	rm -rf 
	rm -rf bin/*.pdb bin/*.mdb bin/*.vshost.exe bin/*.manifest

cleanall:
	rm -rf Runes/obj Runes.suo
	rm -rf bin
